INSERT INTO Dotify.Artist(Name) VALUES('Car Seat Headrest');
INSERT INTO Dotify.Album(AlbumId, ArtistId, RecordYear, Title) VALUES(1, 1, '2010', '4');
INSERT INTO Dotify.Song(SongId, AlbumId, ArtistId, Track, Title, SongUrl) VALUES(1, 1, 1, 5, 'heartless dick', '/home/kragendor/Music/spotify/Car Seat Headrest - 4 - 05 heartless dick.mp3');
INSERT INTO Dotify.Song(SongId, AlbumId, ArtistId, Track, Title, SongUrl) VALUES(2, 1, 1, 4, 'not "kidding" around', '/home/kragendor/Music/spotify/Car Seat Headrest - 4 - 04 not -kidding- around.mp3');
INSERT INTO Dotify.Song(SongId, AlbumId, ArtistId, Track, Title, SongUrl) VALUES(3, 1, 1, 9, 'around', '/home/kragendor/Music/spotify/Car Seat Headrest - 4 - 09 around.mp3');
INSERT INTO Dotify.Song(SongId, AlbumId, ArtistId, Track, Title, SongUrl) VALUES(4, 1, 1, 7, 'feel like daniel johnston', '/home/kragendor/Music/spotify/Car Seat Headrest - 4 - 07 feel like daniel johnston.mp3');
INSERT INTO Dotify.Song(SongId, AlbumId, ArtistId, Track, Title, SongUrl) VALUES(5, 1, 1, 1, 'a good bridge to never cross until there''s no doubt that he''s dead', '/home/kragendor/Music/spotify/Car Seat Headrest - 4 - 01 a good bridge to never cross until there''s no doubt that he''s dead.mp3');
INSERT INTO Dotify.Song(SongId, AlbumId, ArtistId, Track, Title, SongUrl) VALUES(6, 1, 1, 6, 'dickless heart', '/home/kragendor/Music/spotify/Car Seat Headrest - 4 - 06 dickless heart.mp3');
INSERT INTO Dotify.Song(SongId, AlbumId, ArtistId, Track, Title, SongUrl) VALUES(7, 1, 1, 2, 'who even knows', '/home/kragendor/Music/spotify/Car Seat Headrest - 4 - 02 who even knows.mp3');
INSERT INTO Dotify.Song(SongId, AlbumId, ArtistId, Track, Title, SongUrl) VALUES(8, 1, 1, 8, 'the ghost of bob saget', '/home/kragendor/Music/spotify/Car Seat Headrest - 4 - 08 the ghost of bob saget.mp3');
INSERT INTO Dotify.Song(SongId, AlbumId, ArtistId, Track, Title, SongUrl) VALUES(9, 1, 1, 3, 'even the who knows', '/home/kragendor/Music/spotify/Car Seat Headrest - 4 - 03 even the who knows.mp3');
INSERT INTO Dotify.Album(AlbumId, ArtistId, RecordYear, Title) VALUES(2, 1, '2010', '3');
INSERT INTO Dotify.Song(SongId, AlbumId, ArtistId, Track, Title, SongUrl) VALUES(1, 2, 1, 3, 'beach weak', '/home/kragendor/Music/spotify/Car Seat Headrest - 3 - 03 beach weak.mp3');
INSERT INTO Dotify.Song(SongId, AlbumId, ArtistId, Track, Title, SongUrl) VALUES(2, 2, 1, 4, 'foreign song', '/home/kragendor/Music/spotify/Car Seat Headrest - 3 - 04 foreign song.mp3');
INSERT INTO Dotify.Song(SongId, AlbumId, ArtistId, Track, Title, SongUrl) VALUES(3, 2, 1, 1, 'no starving', '/home/kragendor/Music/spotify/Car Seat Headrest - 3 - 01 no starving.mp3');
INSERT INTO Dotify.Song(SongId, AlbumId, ArtistId, Track, Title, SongUrl) VALUES(4, 2, 1, 13, 'oh! starving', '/home/kragendor/Music/spotify/Car Seat Headrest - 3 - 13 oh! starving.mp3');
INSERT INTO Dotify.Song(SongId, AlbumId, ArtistId, Track, Title, SongUrl) VALUES(5, 2, 1, 8, 'summer bummer', '/home/kragendor/Music/spotify/Car Seat Headrest - 3 - 08 summer bummer.mp3');
INSERT INTO Dotify.Song(SongId, AlbumId, ArtistId, Track, Title, SongUrl) VALUES(6, 2, 1, 12, 'beach funeral', '/home/kragendor/Music/spotify/Car Seat Headrest - 3 - 12 beach funeral.mp3');
INSERT INTO Dotify.Song(SongId, AlbumId, ArtistId, Track, Title, SongUrl) VALUES(7, 2, 1, 6, 'sun hot', '/home/kragendor/Music/spotify/Car Seat Headrest - 3 - 06 sun hot.mp3');
INSERT INTO Dotify.Song(SongId, AlbumId, ArtistId, Track, Title, SongUrl) VALUES(8, 2, 1, 11, 'beach death', '/home/kragendor/Music/spotify/Car Seat Headrest - 3 - 11 beach death.mp3');
INSERT INTO Dotify.Song(SongId, AlbumId, ArtistId, Track, Title, SongUrl) VALUES(9, 2, 1, 2, 'portrait of the artist as a young fag', '/home/kragendor/Music/spotify/Car Seat Headrest - 3 - 02 portrait of the artist as a young fag.mp3');
INSERT INTO Dotify.Song(SongId, AlbumId, ArtistId, Track, Title, SongUrl) VALUES(10, 2, 1, 5, 'psst, teenagers, take off your clo', '/home/kragendor/Music/spotify/Car Seat Headrest - 3 - 05 psst, teenagers, take off your clo.mp3');
INSERT INTO Dotify.Song(SongId, AlbumId, ArtistId, Track, Title, SongUrl) VALUES(11, 2, 1, 7, 'beach fagz', '/home/kragendor/Music/spotify/Car Seat Headrest - 3 - 07 beach fagz.mp3');
INSERT INTO Dotify.Song(SongId, AlbumId, ArtistId, Track, Title, SongUrl) VALUES(12, 2, 1, 9, 'ryan north by northwest', '/home/kragendor/Music/spotify/Car Seat Headrest - 3 - 09 ryan north by northwest.mp3');
INSERT INTO Dotify.Song(SongId, AlbumId, ArtistId, Track, Title, SongUrl) VALUES(13, 2, 1, 10, 'beach drugs', '/home/kragendor/Music/spotify/Car Seat Headrest - 3 - 10 beach drugs.mp3');
INSERT INTO Dotify.Album(AlbumId, ArtistId, RecordYear, Title) VALUES(3, 1, '2013', 'Nervous Young Man');
INSERT INTO Dotify.Song(SongId, AlbumId, ArtistId, Track, Title, SongUrl) VALUES(1, 3, 1, 8, 'The Gun Song', '/home/kragendor/Music/spotify/Car Seat Headrest - Nervous Young Man - 08 The Gun Song.mp3');
INSERT INTO Dotify.Album(AlbumId, ArtistId, RecordYear, Title) VALUES(4, 1, '2011', 'Twin Fantasy');
INSERT INTO Dotify.Song(SongId, AlbumId, ArtistId, Track, Title, SongUrl) VALUES(1, 4, 1, 3, 'Stop Smoking', '/home/kragendor/Music/spotify/Car Seat Headrest - Twin Fantasy - 03 Stop Smoking.mp3');
INSERT INTO Dotify.Song(SongId, AlbumId, ArtistId, Track, Title, SongUrl) VALUES(2, 4, 1, 7, 'Cute Thing', '/home/kragendor/Music/spotify/Car Seat Headrest - Twin Fantasy - 07 Cute Thing.mp3');
INSERT INTO Dotify.Song(SongId, AlbumId, ArtistId, Track, Title, SongUrl) VALUES(3, 4, 1, 1, 'My Boy (Twin Fantasy)', '/home/kragendor/Music/spotify/Car Seat Headrest - Twin Fantasy - 01 My Boy (Twin Fantasy).mp3');
INSERT INTO Dotify.Song(SongId, AlbumId, ArtistId, Track, Title, SongUrl) VALUES(4, 4, 1, 8, 'High To Death', '/home/kragendor/Music/spotify/Car Seat Headrest - Twin Fantasy - 08 High To Death.mp3');
INSERT INTO Dotify.Song(SongId, AlbumId, ArtistId, Track, Title, SongUrl) VALUES(5, 4, 1, 6, 'Bodys', '/home/kragendor/Music/spotify/Car Seat Headrest - Twin Fantasy - 06 Bodys.mp3');
INSERT INTO Dotify.Song(SongId, AlbumId, ArtistId, Track, Title, SongUrl) VALUES(6, 4, 1, 5, 'Nervous Young Inhumans', '/home/kragendor/Music/spotify/Car Seat Headrest - Twin Fantasy - 05 Nervous Young Inhumans.mp3');
INSERT INTO Dotify.Song(SongId, AlbumId, ArtistId, Track, Title, SongUrl) VALUES(7, 4, 1, 10, 'Twin Fantasy (Those Boys)', '/home/kragendor/Music/spotify/Car Seat Headrest - Twin Fantasy - 10 Twin Fantasy (Those Boys).mp3');
INSERT INTO Dotify.Song(SongId, AlbumId, ArtistId, Track, Title, SongUrl) VALUES(8, 4, 1, 4, 'Sober To Death', '/home/kragendor/Music/spotify/Car Seat Headrest - Twin Fantasy - 04 Sober To Death.mp3');
INSERT INTO Dotify.Song(SongId, AlbumId, ArtistId, Track, Title, SongUrl) VALUES(9, 4, 1, 9, 'Famous Prophets (Minds)', '/home/kragendor/Music/spotify/Car Seat Headrest - Twin Fantasy - 09 Famous Prophets (Minds).mp3');
INSERT INTO Dotify.Song(SongId, AlbumId, ArtistId, Track, Title, SongUrl) VALUES(10, 4, 1, 2, 'Beach Life-In-Death', '/home/kragendor/Music/spotify/Car Seat Headrest - Twin Fantasy - 02 Beach Life-In-Death.mp3');
INSERT INTO Dotify.Artist(Name) VALUES('Late Night Tales');
INSERT INTO Dotify.Album(AlbumId, ArtistId, RecordYear, Title) VALUES(1, 2, '2015', 'After Dark (Nocturne)');
INSERT INTO Dotify.Song(SongId, AlbumId, ArtistId, Track, Title, SongUrl) VALUES(1, 1, 2, 12, 'Solenoid', '/home/kragendor/Music/spotify/12 - Rodion - Solenoid.mp3');
INSERT INTO Dotify.Song(SongId, AlbumId, ArtistId, Track, Title, SongUrl) VALUES(2, 1, 2, 18, 'Galaxy', '/home/kragendor/Music/spotify/18 - Alex Metric & Oliver - Galaxy.mp3');
INSERT INTO Dotify.Song(SongId, AlbumId, ArtistId, Track, Title, SongUrl) VALUES(3, 1, 2, 8, 'Chained To The Train Of Love', '/home/kragendor/Music/spotify/08 - Coalkitchen - Chained To The Train Of Love.mp3');
INSERT INTO Dotify.Song(SongId, AlbumId, ArtistId, Track, Title, SongUrl) VALUES(4, 1, 2, 17, 'Funky Voodoo (Mang Dynasty Edit)', '/home/kragendor/Music/spotify/17 - Spaghetti Head - Funky Voodoo (Mang Dynasty Edit).mp3');
INSERT INTO Dotify.Song(SongId, AlbumId, ArtistId, Track, Title, SongUrl) VALUES(5, 1, 2, 3, 'Third World', '/home/kragendor/Music/spotify/03 - Paladin - Third World.mp3');
INSERT INTO Dotify.Song(SongId, AlbumId, ArtistId, Track, Title, SongUrl) VALUES(6, 1, 2, 9, 'In Deep', '/home/kragendor/Music/spotify/09 - Matt Dirt - In Deep.mp3');
INSERT INTO Dotify.Song(SongId, AlbumId, ArtistId, Track, Title, SongUrl) VALUES(8, 1, 2, 15, 'Miss Fortune (Chuggy Edit)', '/home/kragendor/Music/spotify/15 - Pink And Black - Miss Fortune (Chuggy Edit).mp3');
INSERT INTO Dotify.Song(SongId, AlbumId, ArtistId, Track, Title, SongUrl) VALUES(9, 1, 2, 2, 'Stop Ou Encore (Disconet Remix)', '/home/kragendor/Music/spotify/02 - Plastic Bertrand - Stop Ou Encore (Disconet Remix).mp3');
INSERT INTO Dotify.Song(SongId, AlbumId, ArtistId, Track, Title, SongUrl) VALUES(10, 1, 2, 16, 'Acid Cake', '/home/kragendor/Music/spotify/16 - Trulz & Robin - Acid Cake.mp3');
INSERT INTO Dotify.Song(SongId, AlbumId, ArtistId, Track, Title, SongUrl) VALUES(11, 1, 2, 4, 'L''Unica Chance', '/home/kragendor/Music/spotify/04 - Adriano Celentano - L''Unica Chance.mp3');
INSERT INTO Dotify.Song(SongId, AlbumId, ArtistId, Track, Title, SongUrl) VALUES(12, 1, 2, 7, 'Celebre', '/home/kragendor/Music/spotify/07 - Harry Wolfman - Celebre.mp3');
INSERT INTO Dotify.Song(SongId, AlbumId, ArtistId, Track, Title, SongUrl) VALUES(13, 1, 2, 14, 'Breezin''', '/home/kragendor/Music/spotify/14 - Emperor Machine - Breezin''.mp3');
INSERT INTO Dotify.Song(SongId, AlbumId, ArtistId, Track, Title, SongUrl) VALUES(14, 1, 2, 5, 'Chocolate City', '/home/kragendor/Music/spotify/05 - Hotel Motel - Chocolate City.mp3');
INSERT INTO Dotify.Song(SongId, AlbumId, ArtistId, Track, Title, SongUrl) VALUES(15, 1, 2, 1, 'Scream And Dance', '/home/kragendor/Music/spotify/01 - Scream And Dance - Scream And Dance.mp3');
INSERT INTO Dotify.Song(SongId, AlbumId, ArtistId, Track, Title, SongUrl) VALUES(16, 1, 2, 13, 'Insect Overlord', '/home/kragendor/Music/spotify/13 - Tornado Wallace - Insect Overlord.mp3');
INSERT INTO Dotify.Song(SongId, AlbumId, ArtistId, Track, Title, SongUrl) VALUES(17, 1, 2, 6, 'The Fall', '/home/kragendor/Music/spotify/06 - Hotel Motel Feat. Snax - The Fall.mp3');
INSERT INTO Dotify.Song(SongId, AlbumId, ArtistId, Track, Title, SongUrl) VALUES(18, 1, 2, 19, 'Back To The Street', '/home/kragendor/Music/spotify/19 - Rudy Norman - Back To The Street.mp3');
INSERT INTO Dotify.Song(SongId, AlbumId, ArtistId, Track, Title, SongUrl) VALUES(19, 1, 2, 10, 'Organic Ceramic', '/home/kragendor/Music/spotify/10 - Hugh Mane - Organic Ceramic.mp3');
INSERT INTO Dotify.Artist(Name) VALUES('Unknown');
INSERT INTO Dotify.Album(AlbumId, ArtistId, RecordYear, Title) VALUES(1, 3, 'Unknown', 'Unknown');
INSERT INTO Dotify.Song(SongId, AlbumId, ArtistId, Track, Title, SongUrl) VALUES(1, 1, 3, 0, 'Unknown', '/home/kragendor/Music/spotify/Car Seat Headrest & Naked Giants - This Must Be The Place (Talking Heads Cover).mp3');
INSERT INTO Dotify.Song(SongId, AlbumId, ArtistId, Track, Title, SongUrl) VALUES(2, 1, 3, 0, 'Unknown', '/home/kragendor/Music/spotify/Car Seat Headrest - Ivy (Frank Ocean Cover_Remix).mp3');
INSERT INTO Dotify.Artist(Name) VALUES('Death Grips');
INSERT INTO Dotify.Album(AlbumId, ArtistId, RecordYear, Title) VALUES(1, 4, '2011', 'Exmilitary');
INSERT INTO Dotify.Song(SongId, AlbumId, ArtistId, Track, Title, SongUrl) VALUES(1, 1, 4, 2, 'Guillotine (It Goes Yah)', '/home/kragendor/Music/spotify/Death Grips - Exmilitary - 02 Guillotine (It Goes Yah).mp3');
INSERT INTO Dotify.Song(SongId, AlbumId, ArtistId, Track, Title, SongUrl) VALUES(2, 1, 4, 3, 'Spread Eagle Cross the Block', '/home/kragendor/Music/spotify/Death Grips - Exmilitary - 03 Spread Eagle Cross the Block.mp3');
INSERT INTO Dotify.Song(SongId, AlbumId, ArtistId, Track, Title, SongUrl) VALUES(3, 1, 4, 11, 'Known for it', '/home/kragendor/Music/spotify/Death Grips - Exmilitary - 11 Known for it.mp3');
INSERT INTO Dotify.Song(SongId, AlbumId, ArtistId, Track, Title, SongUrl) VALUES(4, 1, 4, 8, 'Culture Shock', '/home/kragendor/Music/spotify/Death Grips - Exmilitary - 08 Culture Shock.mp3');
INSERT INTO Dotify.Song(SongId, AlbumId, ArtistId, Track, Title, SongUrl) VALUES(5, 1, 4, 1, 'Beware', '/home/kragendor/Music/spotify/Death Grips - Exmilitary - 01 Beware.mp3');
INSERT INTO Dotify.Song(SongId, AlbumId, ArtistId, Track, Title, SongUrl) VALUES(6, 1, 4, 5, 'Takyon (Death Yon)', '/home/kragendor/Music/spotify/Death Grips - Exmilitary - 05 Takyon (Death Yon).mp3');
INSERT INTO Dotify.Song(SongId, AlbumId, ArtistId, Track, Title, SongUrl) VALUES(7, 1, 4, 4, 'Lord of the Game (ft. Mexican Girl)', '/home/kragendor/Music/spotify/Death Grips - Exmilitary - 04 Lord of the Game (ft. Mexican Girl).mp3');
INSERT INTO Dotify.Song(SongId, AlbumId, ArtistId, Track, Title, SongUrl) VALUES(8, 1, 4, 9, '5D', '/home/kragendor/Music/spotify/Death Grips - Exmilitary - 09 5D.mp3');
INSERT INTO Dotify.Song(SongId, AlbumId, ArtistId, Track, Title, SongUrl) VALUES(9, 1, 4, 7, 'Klink', '/home/kragendor/Music/spotify/Death Grips - Exmilitary - 07 Klink.mp3');
INSERT INTO Dotify.Song(SongId, AlbumId, ArtistId, Track, Title, SongUrl) VALUES(10, 1, 4, 10, 'Thru the Walls', '/home/kragendor/Music/spotify/Death Grips - Exmilitary - 10 Thru the Walls.mp3');
INSERT INTO Dotify.Song(SongId, AlbumId, ArtistId, Track, Title, SongUrl) VALUES(11, 1, 4, 13, 'Blood Creepin', '/home/kragendor/Music/spotify/Death Grips - Exmilitary - 13 Blood Creepin.mp3');
INSERT INTO Dotify.Song(SongId, AlbumId, ArtistId, Track, Title, SongUrl) VALUES(12, 1, 4, 12, 'I Want it I Need it (Death Heated)', '/home/kragendor/Music/spotify/Death Grips - Exmilitary - 12 I Want it I Need it (Death Heated).mp3');
INSERT INTO Dotify.Song(SongId, AlbumId, ArtistId, Track, Title, SongUrl) VALUES(13, 1, 4, 6, 'Cut Throat (Instrumental)', '/home/kragendor/Music/spotify/Death Grips - Exmilitary - 06 Cut Throat (Instrumental).mp3');
